<?php

//////////DATABASE LOGINS////////////

//THIS REQUIRES YOU TO HAVE A TWILIO ACCOUNT

	$DB_ID = "SOMEID";

	$DB_KEY = "SOMEJEY";

	$TWIL_KEY =	"XXXXXXXXXXXXXXXXXXXXXXXXX";
	
	$TWIL_SID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";

	$TWIL_NUMBER = "OUTGOINGTWILIONUMBER";
?>